# Generated by Django 5.2.7 on 2025-10-30 07:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('corn', 'Corn'), ('soybean', 'Soybean'), ('cotton', 'Cotton'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('advisory_text', models.TextField()),
                ('optimal_temp_min', models.FloatField(blank=True, null=True)),
                ('optimal_temp_max', models.FloatField(blank=True, null=True)),
                ('water_requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('planting_window_start', models.DateField(blank=True, null=True)),
                ('planting_window_end', models.DateField(blank=True, null=True)),
                ('irrigation_advice', models.TextField(blank=True, null=True)),
                ('pest_warning', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agriculture advisories',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('emission_reduction', 'Emission Reduction'), ('renewable_energy', 'Renewable Energy'), ('water_management', 'Water Management'), ('agriculture', 'Agriculture'), ('urban_planning', 'Urban Planning'), ('disaster_preparedness', 'Disaster Preparedness'), ('conservation', 'Conservation')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('potential_impact', models.TextField(blank=True, null=True)),
                ('implementation_difficulty', models.IntegerField(help_text='1=Easy, 5=Very Difficult', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('estimated_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('action_items', models.TextField()),
                ('timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('stakeholders', models.TextField(blank=True, null=True)),
                ('data_sources', models.TextField(blank=True, null=True)),
                ('success_examples', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_change', models.FloatField(help_text='Temperature change in Celsius')),
                ('co2_change', models.FloatField(help_text='CO2 change in ppm')),
                ('rainfall_change', models.FloatField(help_text='Rainfall change in percentage')),
                ('predicted_temp_impact', models.FloatField(blank=True, null=True)),
                ('predicted_rainfall_impact', models.FloatField(blank=True, null=True)),
                ('predicted_agriculture_impact', models.TextField(blank=True, null=True)),
                ('predicted_ecosystem_impact', models.TextField(blank=True, null=True)),
                ('simulation_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('extreme_heat', 'Extreme Heat'), ('extreme_cold', 'Extreme Cold'), ('heavy_rain', 'Heavy Rain'), ('drought', 'Drought'), ('storm', 'Storm'), ('flood', 'Flood'), ('high_co2', 'High CO2 Levels'), ('air_quality', 'Poor Air Quality')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('affected_areas', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='api_alert_is_acti_6da449_idx'), models.Index(fields=['severity', '-created_at'], name='api_alert_severit_54212b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('message_text', models.TextField()),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('entities', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='api_chatmes_session_5a7a0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClimateMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('temperature', 'Temperature'), ('rainfall', 'Rainfall'), ('co2', 'CO2 Emissions'), ('humidity', 'Humidity'), ('wind_speed', 'Wind Speed'), ('pressure', 'Atmospheric Pressure')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='api_climate_metric__b4acc3_idx'), models.Index(fields=['location', '-timestamp'], name='api_climate_locatio_8550b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('total_rainfall', models.FloatField(blank=True, null=True)),
                ('avg_humidity', models.FloatField(blank=True, null=True)),
                ('avg_co2', models.FloatField(blank=True, null=True)),
                ('avg_wind_speed', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', '-period_start'], name='api_histori_period__10a2de_idx')],
                'unique_together': {('period_type', 'period_start', 'location')},
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('forecast_date', models.DateTimeField(db_index=True)),
                ('predicted_temperature', models.FloatField()),
                ('predicted_min_temp', models.FloatField(blank=True, null=True)),
                ('predicted_max_temp', models.FloatField(blank=True, null=True)),
                ('predicted_rainfall', models.FloatField(blank=True, null=True)),
                ('predicted_humidity', models.FloatField(blank=True, null=True)),
                ('predicted_wind_speed', models.FloatField(blank=True, null=True)),
                ('predicted_co2', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['forecast_type', 'forecast_date'], name='api_weather_forecas_ba7987_idx'), models.Index(fields=['location', 'forecast_date'], name='api_weather_locatio_51dcb8_idx')],
            },
        ),
    ]
